/*
 * window.SV Daten-Ebene (Stufe 2) – automatisch zusammengesetzt.
 * Ergänzt window.SV (aus data-sv.js) um: erweiterten Wortschatz, Verb-
 * Bedeutungen, Satz-Vorgaben, Grammatik (Titel/Regel/Textstücke) & Lernpfad-
 * Themen auf Schwedisch. Muss NACH data-sv.js geladen werden.
 */
(function () {
  "use strict";
  var SV = window.SV;
  if (!SV) return;
  SV.vocab = SV.vocab || {};
  var extra = {
 "e1": "ett huvud",
 "e2": "håret / hår",
 "e3": "ett öga",
 "e4": "ett öra",
 "e5": "en näsa",
 "e6": "en mun",
 "e7": "en hals",
 "e8": "en axel",
 "e9": "en arm",
 "e10": "en hand",
 "e11": "ett finger",
 "e12": "ett ben",
 "e13": "en fot",
 "e14": "en mage",
 "e15": "en rygg",
 "e16": "ett hjärta",
 "e17": "ett ansikte",
 "e18": "en hud",
 "e19": "ett äpple",
 "e20": "en banan",
 "e21": "en apelsin",
 "e22": "en citron",
 "e23": "en tomat",
 "e24": "en potatis",
 "e25": "en lök",
 "e26": "en ost",
 "e27": "en skinka",
 "e28": "ett ägg",
 "e29": "mjölk",
 "e30": "socker",
 "e31": "salt",
 "e32": "peppar",
 "e33": "olja",
 "e34": "smör",
 "e35": "ris",
 "e36": "pasta",
 "e37": "en soppa",
 "e38": "en sallad",
 "e39": "kött",
 "e40": "en fisk",
 "e41": "grönsaker",
 "e42": "frukt",
 "e43": "en tårta",
 "e44": "en glass",
 "e45": "choklad",
 "e46": "ett vin",
 "e47": "en öl",
 "e48": "juice",
 "e49": "te",
 "e50": "en sked",
 "e51": "en gaffel",
 "e52": "en kniv",
 "e53": "en tallrik",
 "e54": "ett glas",
 "e55": "en kopp",
 "e56": "en flaska",
 "e57": "en dörr",
 "e58": "en vägg",
 "e59": "ett golv",
 "e60": "ett tak",
 "e61": "en trappa",
 "e62": "ett bord",
 "e63": "en stol",
 "e64": "en soffa",
 "e65": "ett skåp",
 "e66": "en spegel",
 "e67": "en lampa",
 "e68": "ett kylskåp",
 "e69": "en dusch",
 "e70": "en handduk",
 "e71": "en tvål",
 "e72": "en trädgård",
 "e73": "en flygplats",
 "e74": "en bank",
 "e75": "posten",
 "e76": "ett sjukhus",
 "e77": "en skola",
 "e78": "ett universitet",
 "e79": "ett museum",
 "e80": "en bio",
 "e81": "en teater",
 "e82": "ett bibliotek",
 "e83": "en park",
 "e84": "en marknad",
 "e85": "ett hotell",
 "e86": "ett rådhus",
 "e87": "ett trafikljus",
 "e88": "ett hörn",
 "e89": "en bro",
 "e90": "ett träd",
 "e91": "en blomma",
 "e92": "gräs",
 "e93": "en skog",
 "e94": "ett berg",
 "e95": "en sjö",
 "e96": "en flod",
 "e97": "en himmel",
 "e98": "ett moln",
 "e99": "en stjärna",
 "e100": "en måne",
 "e101": "en ö",
 "e102": "en vind",
 "e103": "snö",
 "e104": "regn",
 "e105": "jorden",
 "e106": "en hund",
 "e107": "en katt",
 "e108": "en fågel",
 "e109": "en häst",
 "e110": "en ko",
 "e111": "en gris",
 "e112": "en kyckling",
 "e113": "en mus",
 "e114": "ett lejon",
 "e115": "en björn",
 "e116": "ett bi",
 "e117": "en mygga",
 "e118": "en klänning / en kostym",
 "e119": "en kjol",
 "e120": "en tröja",
 "e121": "en skjorta",
 "e122": "strumpor",
 "e123": "ett bälte",
 "e124": "en halsduk",
 "e125": "handskar",
 "e126": "glasögon",
 "e127": "en väska",
 "e128": "en ring",
 "e129": "en lärare",
 "e130": "en elev / student",
 "e131": "en uppgift / läxa",
 "e132": "ett prov",
 "e133": "en bok",
 "e134": "en penna",
 "e135": "papper",
 "e136": "en fråga",
 "e137": "ett svar",
 "e138": "ett ord",
 "e139": "ett språk",
 "e140": "ett tal / nummer",
 "e141": "en klocka",
 "e142": "en chef",
 "e143": "ett yrke",
 "e144": "en mobil",
 "e145": "en dator",
 "e146": "internet",
 "e147": "ett mejl",
 "e148": "en skärm",
 "e149": "ett foto",
 "e150": "en video",
 "e151": "en timme",
 "e152": "en minut",
 "e153": "en dag",
 "e154": "en natt",
 "e155": "ett år",
 "e156": "i går",
 "e157": "senare / efteråt",
 "e158": "måndag",
 "e159": "tisdag",
 "e160": "onsdag",
 "e161": "torsdag",
 "e162": "fredag",
 "e163": "lördag",
 "e164": "söndag",
 "e165": "januari",
 "e166": "februari",
 "e167": "mars",
 "e168": "april",
 "e169": "maj",
 "e170": "juni",
 "e171": "juli",
 "e172": "september",
 "e173": "oktober",
 "e174": "november",
 "e175": "december",
 "e176": "äta",
 "e177": "dricka",
 "e178": "tala / prata",
 "e179": "se",
 "e180": "höra / känna",
 "e181": "skriva",
 "e182": "arbeta / jobba",
 "e183": "bo",
 "e184": "betala",
 "e185": "öppna",
 "e186": "stänga",
 "e187": "börja",
 "e188": "avsluta / sluta",
 "e189": "söka / leta",
 "e190": "ge",
 "e191": "ta",
 "e192": "bära / ta med",
 "e193": "hjälpa",
 "e194": "tro",
 "e195": "hoppas",
 "e196": "svara",
 "e197": "studera / plugga",
 "e198": "springa",
 "e199": "köra",
 "e200": "flyga",
 "e201": "resa",
 "e202": "ha på sig / bära",
 "e203": "vinna",
 "e204": "förlora / tappa",
 "e205": "skratta",
 "e206": "sjunga",
 "e207": "dansa",
 "e208": "tvätta",
 "e209": "använda",
 "e210": "ändra / byta",
 "e211": "prova / försöka",
 "e212": "älska",
 "e213": "reparera / laga",
 "e214": "god",
 "e215": "dålig / elak",
 "e216": "lång",
 "e217": "kort",
 "e218": "hög / lång",
 "e219": "låg / kort",
 "e220": "bred",
 "e221": "trång / smal",
 "e222": "tung",
 "e223": "lätt",
 "e224": "snabb",
 "e225": "långsam",
 "e226": "full",
 "e227": "tom",
 "e228": "ren",
 "e229": "smutsig",
 "e230": "rik",
 "e231": "fattig",
 "e232": "ung",
 "e233": "stark",
 "e234": "svag",
 "e235": "nöjd / glad",
 "e236": "ledsen",
 "e237": "arg",
 "e238": "lugn",
 "e239": "intressant",
 "e240": "tråkig",
 "e241": "rolig / underhållande",
 "e242": "möjlig",
 "e243": "omöjlig",
 "e244": "lika / likadan",
 "e245": "olika / annorlunda",
 "e246": "fri / ledig",
 "e247": "upptagen",
 "e248": "öppen",
 "e249": "stängd",
 "e250": "rätt / riktig",
 "e251": "fel / felaktig",
 "e252": "tid",
 "e253": "ett liv",
 "e254": "en värld",
 "e255": "en människa / person",
 "e256": "kärlek",
 "e257": "tur / lycka",
 "e258": "ett problem",
 "e259": "en idé",
 "e260": "en åsikt",
 "e261": "en sanning",
 "e262": "rädsla",
 "e263": "ett hopp",
 "e264": "en anledning / ett skäl",
 "e265": "ett exempel",
 "e266": "en skillnad",
 "e267": "en historia",
 "e268": "en film",
 "e269": "ett spel / en lek",
 "e270": "en resa",
 "e271": "en semester / lov",
 "e272": "en färg",
 "e273": "ett / en",
 "e274": "två",
 "e275": "tre",
 "e276": "fyra",
 "e277": "fem",
 "e278": "sex",
 "e279": "sju",
 "e280": "åtta",
 "e281": "nio",
 "e282": "tio",
 "e283": "tjugo",
 "e284": "trettio",
 "e285": "hundra",
 "e286": "tusen",
 "e287": "säga",
 "e288": "göra",
 "e289": "bli",
 "e290": "återvända / komma tillbaka",
 "e291": "gå in / komma in",
 "e292": "gå upp / stiga på",
 "e293": "gå ner / stiga av",
 "e294": "gå / promenera",
 "e295": "lägga / sätta / ställa",
 "e296": "ta bort / ta av",
 "e297": "tända / sätta på",
 "e298": "släcka / stänga av",
 "e299": "ringa / kalla",
 "e300": "förklara",
 "e301": "hända / ske",
 "e302": "verka / förefalla",
 "e303": "träffa / möta",
 "e304": "tacka",
 "e305": "lova",
 "e306": "välja",
 "e307": "erbjuda / bjuda",
 "e308": "ge bort / skänka",
 "e309": "låna ut",
 "e310": "sälja",
 "e311": "spendera / göra av med",
 "e312": "spara",
 "e313": "undervisa / lära ut",
 "e314": "upprepa / repetera",
 "e315": "rita",
 "e316": "bygga",
 "e317": "ha sönder / krossa",
 "e318": "lämna / låta",
 "e319": "hålla / behålla",
 "e320": "vända / svänga",
 "e321": "stanna",
 "e322": "fortsätta",
 "e323": "sluta",
 "e324": "sätta sig",
 "e325": "röra sig",
 "e326": "känna sig",
 "e327": "ha roligt / roa sig",
 "e328": "bli arg",
 "e329": "oroa sig",
 "e330": "bli kär / förälska sig",
 "e331": "gifta sig",
 "e332": "en turist",
 "e333": "en guide",
 "e334": "en karta",
 "e335": "bagage",
 "e336": "en bokning / reservation",
 "e337": "ett pass",
 "e338": "ett dokument / en legitimation",
 "e339": "en färja",
 "e340": "en båt",
 "e341": "ett fartyg",
 "e342": "en cykel",
 "e343": "hyra",
 "e344": "ett vykort",
 "e345": "ett monument",
 "e346": "en katedral / domkyrka",
 "e347": "en fontän",
 "e348": "ett centrum",
 "e349": "besöka",
 "e350": "koppla av / slappna av",
 "e351": "en sommar",
 "e352": "en vinter",
 "e353": "en vår",
 "e354": "en höst",
 "e355": "en restaurang",
 "e356": "en trattoria",
 "e357": "en pizzeria",
 "e358": "en bar / ett kafé",
 "e359": "en meny",
 "e360": "en förrätt",
 "e361": "första rätten",
 "e362": "huvudrätten",
 "e363": "ett tillbehör",
 "e364": "en efterrätt / dessert",
 "e365": "dricks",
 "e366": "kaffe",
 "e367": "en cappuccino",
 "e368": "en pizza",
 "e369": "smaka / provsmaka",
 "e370": "en smak",
 "e371": "is",
 "e372": "en fru / hustru",
 "e373": "en svärfar",
 "e374": "en släkting",
 "e375": "en gammelfarfar",
 "e376": "en pojkvän / fästman",
 "e377": "ett par",
 "e378": "en årsdag",
 "e379": "växa / växa upp / uppfostra",
 "e380": "likna",
 "e381": "ett barn",
 "e382": "en flicka",
 "e383": "ett nyfött barn",
 "e384": "en nappflaska",
 "e385": "en napp",
 "e386": "en vagga",
 "e387": "krypa",
 "e388": "gosa / mysa",
 "e389": "en gunga",
 "e390": "en saga",
 "e391": "en teckning",
 "e392": "naturen",
 "e393": "ett djur",
 "e394": "en äng",
 "e395": "en kulle",
 "e396": "en dal",
 "e397": "en solnedgång",
 "e398": "en soluppgång / gryning",
 "e399": "ett löv / blad",
 "e400": "luft",
 "e401": "en eld",
 "e402": "en våg",
 "e403": "en fjäril",
 "e404": "en regnbåge",
 "e405": "ett åskväder",
 "e406": "skydda",
 "e407": "en själ",
 "e408": "en ande",
 "e409": "ett sinne / förstånd",
 "e410": "en kropp",
 "e411": "en meditation",
 "e412": "meditera",
 "e413": "andas",
 "e414": "en andning / ett andetag",
 "e415": "be",
 "e416": "en bön",
 "e417": "en tro",
 "e418": "fred / frid",
 "e419": "lugn",
 "e420": "energi",
 "e421": "en balans / jämvikt",
 "e422": "tacksamhet",
 "e423": "välbefinnande",
 "e424": "läka / bli frisk",
 "e425": "tystnad",
 "e426": "ett ljus",
 "e427": "drömma",
 "e428": "en dröm",
 "e429": "ett universum",
 "e430": "ett öde",
 "e431": "lycka / glädje",
 "e432": "ny",
 "e433": "söt / gullig",
 "e434": "duktig / bra",
 "e435": "frisk / sund",
 "e436": "salt",
 "e437": "färsk / sval",
 "e438": "hård",
 "e439": "ljus / klar",
 "e440": "mörk",
 "e441": "sann / äkta",
 "e442": "falsk / oäkta",
 "e443": "säker",
 "e444": "farlig",
 "e445": "användbar / nyttig",
 "e446": "nödvändig",
 "e447": "normal",
 "e448": "konstig / underlig",
 "e449": "enkel",
 "e450": "komplicerad",
 "e451": "berömd",
 "e452": "intelligent / smart",
 "e453": "djup",
 "e454": "artig / väluppfostrad",
 "e455": "nervös",
 "e456": "blyg",
 "e457": "modig",
 "e458": "generös",
 "e459": "ärlig",
 "e460": "lat",
 "e461": "aktiv",
 "e462": "en sjuksköterska",
 "e463": "en kock",
 "e464": "en expedit / försäljare",
 "e465": "en polis",
 "e466": "en bonde",
 "e467": "en arbetare",
 "e468": "en konstnär",
 "e469": "en journalist",
 "e470": "en sjukdom",
 "e471": "en hosta",
 "e472": "en smärta / värk",
 "e473": "ett sår",
 "e474": "ett recept",
 "e475": "en ambulans",
 "e476": "blod",
 "e477": "ett ben",
 "e478": "en muskel",
 "e479": "en diet",
 "e480": "ett plåster",
 "e481": "vila",
 "e482": "bli sjuk",
 "e483": "en spruta / ett stick",
 "e484": "en känsla",
 "e485": "ilska",
 "e486": "sorg",
 "e487": "glädje",
 "e488": "en överraskning",
 "e489": "tristess / leda",
 "e490": "stress",
 "e491": "mod",
 "e492": "stolt",
 "e493": "svartsjuk",
 "e494": "besviken",
 "e495": "överraskad",
 "e496": "uttråkad",
 "e497": "upprymd / rörd",
 "e498": "nöjd / tillfredsställd",
 "e499": "ett vardagsrum",
 "e500": "en balkong",
 "e501": "ett innertak",
 "e502": "en hiss",
 "e503": "en dörrklocka",
 "e504": "en kudde",
 "e505": "en filt",
 "e506": "en tandborste",
 "e507": "en tandkräm",
 "e508": "en kran",
 "e509": "en kvast",
 "e510": "en tvättmaskin",
 "e511": "sopor / skräp",
 "e512": "uppvärmning",
 "e513": "en gardin",
 "e514": "ett kvitto",
 "e515": "ett pris",
 "e516": "en rabatt",
 "e517": "ett erbjudande",
 "e518": "en plånbok",
 "e519": "ett kreditkort",
 "e520": "kontanter",
 "e521": "gratis / kostnadsfri",
 "e522": "en lön",
 "e523": "en kostnad",
 "e524": "ett klimat",
 "e525": "en temperatur",
 "e526": "molnig",
 "e527": "en dimma",
 "e528": "åska",
 "e529": "en blixt",
 "e530": "ett paraply",
 "e531": "blöt / våt",
 "e532": "torr",
 "e533": "ett ögonblick / en stund",
 "e534": "en framtid",
 "e535": "det förflutna / dåtid",
 "e536": "ett århundrade / sekel",
 "e537": "genast / med en gång",
 "e538": "ännu / fortfarande",
 "e539": "redan",
 "e540": "vanligtvis",
 "e541": "ibland",
 "e542": "varje",
 "e543": "äntligen",
 "e544": "plötsligt",
 "e545": "ovanför / uppe",
 "e546": "under / nere",
 "e547": "inne / in",
 "e548": "ute / ut",
 "e549": "framför / framme",
 "e550": "bakom / bakåt",
 "e551": "bredvid",
 "e552": "en ingång",
 "e553": "en utgång",
 "e554": "en våning",
 "e555": "en tv",
 "e556": "en radio",
 "e557": "en tidning",
 "e558": "en tidskrift",
 "e559": "en nyhet",
 "e560": "ett samtal",
 "e561": "ett lösenord",
 "e562": "en webbplats / hemsida",
 "e563": "ladda ner",
 "e564": "surfa",
 "e565": "trä",
 "e566": "järn",
 "e567": "guld",
 "e568": "silver",
 "e569": "plast",
 "e570": "glas",
 "e571": "en sten",
 "e572": "bomull",
 "e573": "vilja",
 "e574": "kunna / få",
 "e575": "måste / böra",
 "e576": "föredra",
 "e577": "hata",
 "e578": "kyssa / pussa",
 "e579": "le",
 "e580": "skrika",
 "e581": "skära / klippa",
 "e582": "hälla / spilla",
 "e583": "röra / blanda",
 "e584": "lägga till / tillsätta",
 "e585": "koka",
 "e586": "steka / fritera",
 "e587": "berätta",
 "e588": "beskriva",
 "e589": "kontrollera",
 "e590": "skriva under / signera",
 "e591": "fylla i",
 "e592": "skicka / sända",
 "e593": "få / ta emot",
 "e594": "skicka",
 "e595": "förbereda / laga",
 "e596": "städa / plocka undan",
 "e597": "torka",
 "e598": "stryka",
 "e599": "hyra / hyra ut",
 "e600": "prata / snacka"
};
  Object.keys(extra).forEach(function (k) { SV.vocab[k] = extra[k]; });
  SV.verbs = {
 "essere": "vara",
 "avere": "ha",
 "fare": "göra",
 "dire": "säga",
 "potere": "kunna",
 "volere": "vilja",
 "dovere": "måste",
 "sapere": "veta / kunna",
 "stare": "vara / må",
 "andare": "gå / åka",
 "venire": "komma",
 "dare": "ge",
 "tenere": "hålla",
 "rimanere": "stanna",
 "bere": "dricka",
 "uscire": "gå ut",
 "riuscire": "lyckas",
 "salire": "stiga upp",
 "morire": "dö",
 "scegliere": "välja",
 "togliere": "ta bort",
 "spegnere": "stänga av",
 "parlare": "tala",
 "trovare": "hitta",
 "lasciare": "lämna",
 "guardare": "titta / se på",
 "passare": "gå förbi / tillbringa",
 "portare": "ta med / bära",
 "pensare": "tänka",
 "tornare": "återvända",
 "aspettare": "vänta",
 "cercare": "söka",
 "chiamare": "ropa / heta",
 "sembrare": "verka / förefalla",
 "entrare": "komma in",
 "ricordare": "minnas",
 "arrivare": "anlända",
 "diventare": "bli",
 "mangiare": "äta",
 "comprare": "köpa",
 "giocare": "leka / spela",
 "lavorare": "arbeta",
 "studiare": "lära sig / studera",
 "amare": "älska",
 "ascoltare": "lyssna",
 "guidare": "köra / styra",
 "cominciare": "börja",
 "aiutare": "hjälpa",
 "cambiare": "byta / ändra",
 "incontrare": "träffa",
 "spiegare": "förklara",
 "pagare": "betala",
 "abitare": "bo",
 "lavare": "tvätta",
 "cucinare": "laga mat",
 "suonare": "spela / ringa",
 "viaggiare": "resa",
 "telefonare": "ringa",
 "camminare": "gå / promenera",
 "dimenticare": "glömma",
 "sperare": "hoppas",
 "provare": "försöka / prova",
 "usare": "använda",
 "tagliare": "skära",
 "cantare": "sjunga",
 "vedere": "se",
 "prendere": "ta",
 "credere": "tro",
 "mettere": "ställa / lägga",
 "vivere": "leva",
 "chiedere": "fråga / be",
 "leggere": "läsa",
 "scrivere": "skriva",
 "perdere": "förlora",
 "chiudere": "stänga",
 "conoscere": "känna",
 "correre": "springa",
 "decidere": "bestämma",
 "ripetere": "upprepa",
 "rispondere": "svara",
 "ricevere": "ta emot",
 "vincere": "vinna",
 "spendere": "spendera",
 "vendere": "sälja",
 "piangere": "gråta",
 "sentire": "höra / känna",
 "dormire": "sova",
 "aprire": "öppna",
 "offrire": "erbjuda",
 "seguire": "följa",
 "partire": "avresa",
 "servire": "tjäna / behövas",
 "capire": "förstå",
 "finire": "avsluta",
 "preferire": "föredra",
 "pulire": "städa",
 "costruire": "bygga",
 "spedire": "skicka",
 "guarire": "bota / tillfriskna",
 "unire": "förena",
 "colpire": "träffa / slå",
 "fornire": "leverera",
 "garantire": "garantera",
 "gestire": "förvalta / sköta",
 "inserire": "infoga",
 "restituire": "återlämna",
 "riferire": "rapportera",
 "sostituire": "ersätta",
 "stabilire": "fastställa",
 "suggerire": "föreslå",
 "chiarire": "klargöra",
 "reagire": "reagera",
 "piacere": "behaga / tycka om",
 "tradurre": "översätta",
 "raccogliere": "samla / plocka",
 "chiamarsi": "heta",
 "alzarsi": "stiga upp",
 "svegliarsi": "vakna",
 "lavarsi": "tvätta sig",
 "vestirsi": "klä på sig",
 "sentirsi": "känna sig",
 "divertirsi": "roa sig",
 "riposarsi": "vila sig",
 "prepararsi": "förbereda sig",
 "arrabbiarsi": "bli arg",
 "annoiarsi": "ha tråkigt",
 "addormentarsi": "somna",
 "ricordarsi": "minnas",
 "fermarsi": "stanna",
 "occuparsi": "ta hand om",
 "truccarsi": "sminka sig",
 "sedersi": "sätta sig",
 "trasferirsi": "flytta"
};
  SV.sentences = SV.sentences || {};
  var sent = {
 "s001": "Vi åker bil till Bologna.",
 "s002": "På lördag kommer vi fram till Italien.",
 "s003": "Vi stannar två dagar hos mor- och farföräldrarna.",
 "s004": "Om tre dagar åker vi iväg till havet.",
 "s005": "Vi tar färjan till Sardinien.",
 "s006": "Min svärmor besöker oss i kväll.",
 "s007": "Mormor kramar bebisen.",
 "s008": "Vi kommer bra överens med min svärmor.",
 "s009": "Bebisen kryper till mormor.",
 "s010": "Bebisen drar sig upp längs soffan.",
 "s011": "Bebisen ramlar och gråter.",
 "s012": "Barnstolen står på restaurangen.",
 "s013": "Vi sätter på bebisen haklappen.",
 "s014": "Bebisen äter en bit bröd.",
 "s015": "Mormor matar bebisen.",
 "s016": "På stranden smörjer vi in bebisen med solkräm.",
 "s017": "Vi sätter parasollet i sanden.",
 "s018": "Vi går och simmar i havet.",
 "s019": "Vid havet stannar vi två veckor.",
 "s020": "På söndag tittar vi på solnedgången.",
 "s021": "På restaurangen äter vi pasta.",
 "s022": "Vi skulle vilja ha två kaffe, tack.",
 "s023": "Hur mycket kostar menyn?",
 "s024": "Vi betalar i kassan.",
 "s025": "Jag tänker laga mat i kväll.",
 "s026": "Medan bebisen sover lagar jag mat.",
 "s027": "Jag åt frukost i morse.",
 "s028": "Vi gick på restaurang i går kväll.",
 "s029": "Bebisen sov hela dagen.",
 "s030": "Jag ringer min mamma.",
 "s031": "Vem är det som talar? Det är Anna.",
 "s032": "Jag har en bror som bor i Italien.",
 "s033": "Mina väninnor kommer hem till mig i kväll.",
 "s034": "Följer du med mig till parken?",
 "s035": "Jag går till läkaren.",
 "s036": "Jag bor i en stor lägenhet.",
 "s037": "Barnvagnen är i bilen.",
 "s038": "Vi tar en promenad med barnvagnen.",
 "s039": "Morfar leker med bebisen.",
 "s040": "Jag är trött men lycklig.",
 "s041": "Jag mår bra, tack.",
 "s042": "Jag är sömnig.",
 "s043": "I dag är det varmt.",
 "s044": "Det har varit fint väder.",
 "s045": "I mitten av augusti åker vi till Bologna.",
 "s046": "Vi tillbringar resten av sommaren vid havet.",
 "s047": "Det är min svärmors bil.",
 "s048": "Jag håller på att klä på bebisen.",
 "s049": "Färjan är på väg att avgå.",
 "s050": "Jag träffar min man i kväll.",
 "s051": "Jag kramar henne.",
 "s052": "Jag känner henne inte.",
 "s053": "Min mamma och jag går på bio.",
 "s054": "Vi tar med en present till mormor.",
 "s055": "Jag tänker ta hand om tvätten.",
 "s056": "Parasollet står på sanden.",
 "s057": "Jag går till kassan.",
 "s058": "Vi tillbringar två veckor vid kusten hos mor- och farföräldrarna.",
 "s059": "Min man lagar mat åt oss.",
 "s060": "Jag kommer från Bologna."
};
  var vex = {
 "v001_ex": "Vi tar tåget till Rom.",
 "v002_ex": "Flygplanet flyger till Italien.",
 "v003_ex": "Jag packar väskan.",
 "v004_ex": "Vi köper biljetterna.",
 "v005_ex": "Stationen ligger i närheten.",
 "v006_ex": "I morgon reser vi iväg.",
 "v007_ex": "Vi kommer fram på kvällen.",
 "v008_ex": "Notan, tack!",
 "v009_ex": "Servitören kommer med vattnet.",
 "v010_ex": "Vi beställer en pizza.",
 "v011_ex": "Jag dricker vatten.",
 "v012_ex": "Brödet är färskt.",
 "v013_ex": "Vi äter frukost tillsammans.",
 "v014_ex": "Lunchen är klockan ett.",
 "v015_ex": "Middagen är klar.",
 "v016_ex": "Bebisen är hungrig.",
 "v017_ex": "Jag är törstig.",
 "v018_ex": "Mormor bor i Bologna.",
 "v019_ex": "Morfar läser en tidning.",
 "v020_ex": "Min svärmor lagar god mat.",
 "v021_ex": "Mina föräldrar kommer i morgon.",
 "v022_ex": "Min syster bor i Rom.",
 "v023_ex": "Min man arbetar mycket.",
 "v024_ex": "Mormor kramar bebisen.",
 "v025_ex": "Barnvagnen är i bilen.",
 "v026_ex": "Vi byter blöjan.",
 "v027_ex": "Bebisen sitter i barnstolen.",
 "v028_ex": "Bebisen sover på eftermiddagen.",
 "v029_ex": "Bebisen gråter på natten.",
 "v030_ex": "Vi leker med bebisen.",
 "v031_ex": "Leksaken ligger på golvet.",
 "v032_ex": "Vi går till stranden.",
 "v033_ex": "Havet är varmt.",
 "v034_ex": "Parasollet står på sanden.",
 "v035_ex": "Bebisen leker i sanden.",
 "v036_ex": "Jag letar efter baddräkten.",
 "v037_ex": "Vi behöver solkräm.",
 "v038_ex": "Vid havet simmar vi varje dag.",
 "v039_ex": "Jag är hemma.",
 "v040_ex": "Köket är litet.",
 "v041_ex": "I kväll lagar jag mat.",
 "v042_ex": "Jag tar hand om tvätten.",
 "v043_ex": "Vi städar huset.",
 "v044_ex": "Jag köper brödet.",
 "v045_ex": "Affären är stängd.",
 "v046_ex": "I dag stannar vi hemma.",
 "v047_ex": "I morgon åker vi till havet.",
 "v048_ex": "Jag är trött.",
 "v049_ex": "Bebisen är lycklig.",
 "v050_ex": "I dag är det varmt.",
 "v051_ex": "På morgonen är det kallt.",
 "v052_ex": "I dag regnar det.",
 "v053_ex": "Vi stannar en vecka.",
 "v054_ex": "Månaden augusti är het.",
 "v055_ex": "På morgonen dricker jag kaffe.",
 "v056_ex": "På kvällen är vi trötta.",
 "v057_ex": "Jag går upp tidigt.",
 "v058_ex": "Vi kommer fram sent.",
 "v059_ex": "Bebisen sover i sängen.",
 "v060_ex": "Rummet är stort.",
 "v061_ex": "Badrummet är där.",
 "v062_ex": "Jag öppnar fönstret.",
 "v063_ex": "Jag går till läkaren.",
 "v064_ex": "Apoteket är stängt.",
 "v065_ex": "Bebisen är sjuk.",
 "v066_ex": "Jag går till mataffären.",
 "v067_ex": "Jag har inga pengar.",
 "v068_ex": "Bilen är dyr.",
 "v069_ex": "Jag förstår inte.",
 "v070_ex": "Jag lär mig italienska.",
 "v071_ex": "Morfar läser en bok.",
 "v072_ex": "I dag skiner solen.",
 "v073_ex": "Jag ger dig ett råd.",
 "v074_ex": "Jag rekommenderar den här restaurangen.",
 "v075_ex": "Jag klarar det inte.",
 "v076_ex": "Hälsan är viktig.",
 "v077_ex": "Vi måste skydda miljön.",
 "v078_ex": "Jag vill förbättra min italienska.",
 "v079_ex": "Vi måste bestämma oss nu.",
 "v080_ex": "Det är ett svårt val.",
 "v081_ex": "Jag bokar ett bord.",
 "v082_ex": "Jag har en tid i morgon.",
 "v083_ex": "Mina föräldrar tillåter det inte.",
 "v084_ex": "Det är förbjudet att röka.",
 "v085_ex": "Trots regnet går vi ut.",
 "v086_ex": "Det var en fin upplevelse.",
 "v087_ex": "Jag har huvudvärk.",
 "v088_ex": "Bebisen har feber.",
 "v089_ex": "Jag tar medicinen.",
 "v090_ex": "Jag är förkyld.",
 "v091_ex": "Jag har ont i tanden.",
 "v092_ex": "Jag köper nya kläder.",
 "v093_ex": "T-shirten är röd.",
 "v094_ex": "Byxorna är för stora.",
 "v095_ex": "Skorna är nya.",
 "v096_ex": "Ta med jackan.",
 "v097_ex": "Bebisen har en mössa.",
 "v098_ex": "Bilen är röd.",
 "v099_ex": "Det vita vinet är gott.",
 "v100_ex": "Kaffet är svart.",
 "v101_ex": "Äpplet är grönt.",
 "v102_ex": "Havet är blått.",
 "v103_ex": "Solen är gul.",
 "v104_ex": "Staden är vacker.",
 "v105_ex": "Gatan är lång.",
 "v106_ex": "Torget är stort.",
 "v107_ex": "Kyrkan är gammal.",
 "v108_ex": "Restaurangen ligger till höger.",
 "v109_ex": "Apoteket ligger till vänster.",
 "v110_ex": "Gå rakt fram.",
 "v111_ex": "Stationen ligger nära.",
 "v112_ex": "Havet ligger långt bort.",
 "v113_ex": "Arbetet är intressant.",
 "v114_ex": "Jag går till kontoret.",
 "v115_ex": "Mötet är klockan tio.",
 "v116_ex": "Min kollega är trevlig.",
 "v117_ex": "Jag tjänar tillräckligt.",
 "v118_ex": "Vi går hem.",
 "v119_ex": "Följer du med mig?",
 "v120_ex": "Jag vet inte.",
 "v121_ex": "Jag känner Rom väl.",
 "v122_ex": "Jag tänker på dig.",
 "v123_ex": "Jag hittar inte nyckeln.",
 "v124_ex": "Jag väntar på dig.",
 "v125_ex": "Jag frågar servitören.",
 "v126_ex": "Huset är stort.",
 "v127_ex": "Bebisen är liten.",
 "v128_ex": "Dagen är fin.",
 "v129_ex": "Vädret är dåligt.",
 "v130_ex": "Övningen är svår.",
 "v131_ex": "Frågan är lätt.",
 "v132_ex": "Jag är trött men lycklig.",
 "v133_ex": "Jag dricker alltid kaffe.",
 "v134_ex": "Jag röker aldrig.",
 "v135_ex": "Vi går ofta till havet.",
 "v136_ex": "Kanske regnar det.",
 "v137_ex": "Hej, hur mår du?",
 "v138_ex": "God morgon allihop!",
 "v139_ex": "God kväll!",
 "v140_ex": "Tack så mycket!",
 "v141_ex": "Ingen orsak!",
 "v142_ex": "En kaffe, tack.",
 "v143_ex": "Ursäkta, vad är klockan?",
 "v144_ex": "Jag är väldigt ledsen.",
 "v145_ex": "Hur mår du i dag?",
 "v146_ex": "Trevligt att träffas, jag heter Anna.",
 "v147_ex": "Jag hälsar på grannarna.",
 "v148_ex": "Jag bjuder dig på middag.",
 "v149_ex": "Tack för inbjudan.",
 "v150_ex": "Jag presenterar min man för dig.",
 "v151_ex": "Grannen är väldigt trevlig.",
 "v152_ex": "Din väninna är sympatisk.",
 "v153_ex": "Vi äter tillsammans.",
 "v154_ex": "Jag kommer gärna.",
 "v155_ex": "Vi är överens.",
 "v156_ex": "En present till mormor.",
 "v157_ex": "Festen är på lördag.",
 "v158_ex": "I dag är det min födelsedag.",
 "v159_ex": "Vi firar födelsedagen.",
 "v160_ex": "Min vän heter Marco.",
 "v161_ex": "Min väninna kommer i kväll.",
 "v162_ex": "Grannen är hemma.",
 "v163_ex": "Min familj är stor.",
 "v164_ex": "Min son är liten.",
 "v165_ex": "Min dotter sover.",
 "v166_ex": "Jag har en bror.",
 "v167_ex": "Mormor älskar sina barnbarn.",
 "v168_ex": "Min moster lagar god mat.",
 "v169_ex": "Min morbror kommer i morgon.",
 "v170_ex": "Min kusin bor i Rom.",
 "v171_ex": "Jag är gift.",
 "v172_ex": "Bröllopet är i juni.",
 "v173_ex": "Jag tycker om dig.",
 "v174_ex": "Barnen bråkar.",
 "v175_ex": "Jag vaknar tidigt.",
 "v176_ex": "Jag går upp klockan sju.",
 "v177_ex": "Jag tvättar mig på morgonen.",
 "v178_ex": "Barnet klär på sig.",
 "v179_ex": "På kvällen vilar jag.",
 "v180_ex": "Bebisen somnar snabbt.",
 "v181_ex": "Jag handlar mat.",
 "v182_ex": "Jag diskar efter maten.",
 "v183_ex": "I kväll går vi ut.",
 "v184_ex": "Jag stannar hemma.",
 "v185_ex": "Jag glömmer alltid nycklarna.",
 "v186_ex": "Jag minns väl.",
 "v187_ex": "Var är nyckeln?",
 "v188_ex": "Telefonen ringer.",
 "v189_ex": "Jag ringer min mamma.",
 "v190_ex": "Jag skriver ett meddelande.",
 "v191_ex": "Jag lyssnar på musik.",
 "v192_ex": "Musiken är fin.",
 "v193_ex": "På kvällen ser vi på tv."
};
  Object.keys(sent).forEach(function (k) { SV.sentences[k] = sent[k]; });
  Object.keys(vex).forEach(function (k) { SV.sentences[k] = vex[k]; });
  SV.grammar = {
 "g_prep_a_in": {
  "title": "Prepositioner: a / in vid platser",
  "rule": "**a** vid **städer**: *a Bologna, a Roma, a Milano*.\n**in** vid **länder & regioner**: *in Italia, in Sardegna, in Toscana*.\nVid transportmedel: **in** → *in macchina, in treno, in aereo*."
 },
 "g_prep_da_di": {
  "title": "Prepositioner: da / di",
  "rule": "**da** = härkomst/ursprung ('från') och 'till någon': *vengo **da** Bologna, vado **dal** medico, dai nonni*.\n**di** = tillhörighet ('någons'): *la macchina **di** mia suocera*."
 },
 "g_conj_are": {
  "title": "Konjugation: regelbundna -are-verb (presens)",
  "rule": "Ändelser för **-are**-verb (parlare):\nio parl**o** · tu parl**i** · lui/lei parl**a** · noi parl**iamo** · voi parl**ate** · loro parl**ano**.\nObservera 3:e pers. plural: **-ano** (costano, mangiano, giocano)."
 },
 "g_conj_special": {
  "title": "Presens: särskilda former (h-inskott & -isc-)",
  "rule": "Vissa **-are**-verb får ett **h** framför **-i** och **-iamo**, så att det hårda k/g-ljudet behålls:\n**-care**: cercare → tu cer**chi**, noi cer**chiamo**; giocare → gio**chi**, gio**chiamo**.\n**-gare**: pagare → tu pa**ghi**, noi pa**ghiamo**; spiegare → spie**ghi**.\nVid **-iare/-ciare/-giare** skriver man bara **ett i**: mangiare → tu man**gi**, noi man**giamo**; studiare → tu stu**di**; cominciare → tu comin**ci**.\nMånga **-ire**-verb skjuter in **-isc-**: capire → cap**isco**, cap**isci**, cap**isce**, cap**iscono** – men **noi cap**iamo**, voi cap**ite** (utan -isc-)."
 },
 "g_conj_ere_ire": {
  "title": "Konjugation: -ere / -ire-verb (presens)",
  "rule": "**-ere** (prendere): prend**o**, prend**i**, prend**e**, prend**iamo**, prend**ete**, prend**ono**.\n**-ire** (dormire): dorm**o**, dorm**i**, dorm**e**, dorm**iamo**, dorm**ite**, dorm**ono**.\nNågra -ire med **-isc-**: capire → cap**isco**, cap**isci**, cap**isce**."
 },
 "g_passato_prossimo": {
  "title": "Passato Prossimo (förfluten tid)",
  "rule": "Bildas med **avere** eller **essere** + particip.\nDe flesta verb: **avere** → *ho mangiato, ho dormito, ho fatto*.\nRörelse-/tillståndsverb: **essere** → *sono andato/a, siamo partiti/e*.\nVid **essere** anpassar sig participet: *siamo andat**i**, sono andat**a***."
 },
 "g_possessive": {
  "title": "Possessiv & familjemedlemmar",
  "rule": "Artikel + possessiv + substantiv måste **stämma överens**: *le mie amiche, i miei amici*.\n**Undantag:** familjemedlemmar **i singular** utan artikel: *mio marito, mia mamma, mia sorella*.\nMen plural med artikel: *i miei genitori*; smeknamn med artikel: *la mia mamma*."
 },
 "g_prep_articolate": {
  "title": "Sammansatta prepositioner (nel, sul, al, del…)",
  "rule": "Preposition + bestämd artikel smälter samman:\n**a**+il=**al**, a+la=**alla**, a+i=**ai** · **in**+il=**nel**, in+la=**nella** · **su**+il=**sul**, su+la=**sulla** · **di**+il=**del** · **da**+il=**dal**, da+i=**dai**.\nFramför **obestämd** artikel smälter de INTE samman: *in un, a un*."
 },
 "g_reflexive": {
  "title": "Reflexiva verb (mi alzo, mi occupo…)",
  "rule": "Reflexivt pronomen framför verbet: **mi, ti, si, ci, vi, si**.\nalzarsi: mi alz**o**, ti alz**i**, si alz**a**, ci alz**iamo**, vi alz**ate**, si alz**ano**.\nEfter modalverb/infinitiv **läggs pronomenet till & anpassas**: *voglio alzarmi, devo occuparmi*."
 },
 "g_modal": {
  "title": "Modalverb: potere, volere, dovere",
  "rule": "Oregelbundna i presens, sedan **+ infinitiv**:\n**potere** (kunna): posso, puoi, può, possiamo, potete, possono.\n**volere** (vilja): voglio, vuoi, vuole, vogliamo, volete, vogliono.\n**dovere** (måste): devo, devi, deve, dobbiamo, dovete, devono."
 },
 "g_pronouns": {
  "title": "Objektpronomen (direkta & indirekta)",
  "rule": "**Direkta** (vem/vad): mi, ti, **lo, la**, ci, vi, **li, le**. → *Lo vedo* (jag ser honom).\n**Indirekta** (åt vem): mi, ti, **gli, le**, ci, vi, **gli**. → *Le parlo* (jag talar med henne).\nlo/la blir framför vokal **l'**: *L'amo*."
 },
 "g_comparativo": {
  "title": "Komparativ (più… di / meno… di / come)",
  "rule": "**più … di** = mer än · **meno … di** = mindre än · **(così)… come** = lika … som.\n*di* smälter samman med artikeln: più grande **della** casa.\nFramför två substantiv i jämförelsen står **che**: *più turisti **che** abitanti*."
 },
 "g_stare": {
  "title": "stare + gerundio & stare per (håller på / strax innan)",
  "rule": "**stare + gerundio** = att just hålla på: *sto mangiando, stai facendo*.\nGerundio: -are → **-ando**, -ere/-ire → **-endo**.\n**stare per + infinitiv** = strax innan: *sto per partire, il treno sta per arrivare*."
 },
 "a1_essere_avere": {
  "title": "essere & avere (presens)",
  "rule": "**essere** (vara): sono, sei, è, siamo, siete, sono.\n**avere** (ha): ho, hai, ha, abbiamo, avete, hanno.\n*essere* för tillstånd/härkomst (*Sono di Roma*), *avere* för ägande/ålder (*Ho 30 anni*)."
 },
 "a1_sostantivi": {
  "title": "Substantiv: genus, plural & artikel",
  "rule": "Plural: **-o → -i** (libro→libri), **-a → -e** (casa→case), **-e → -i** (fiore→fiori).\nBestämd artikel: **il/lo/l'/la** (sing.), **i/gli/le** (plur.). Obestämd: **un/uno/una/un'**.\n*lo/uno* framför s+konsonant, z, ps (lo zaino, uno studente). Delningsartikel **del/della/dei** = 'lite/några'."
 },
 "a1_fragen": {
  "title": "Frågor & frågeord",
  "rule": "**Ja/nej-fråga**: samma mening som påståendet, bara med frågeintonation (*Parli italiano?*).\n**Frågeord**: chi (vem), che cosa/cosa (vad), dove (var), quando (när), come (hur), perché (varför), quanto (hur mycket), quale (vilken)."
 },
 "a1_verbi_irregolari": {
  "title": "Oregelbundna verb: fare, andare, stare, venire",
  "rule": "**fare**: faccio, fai, fa, facciamo, fate, fanno.\n**andare**: vado, vai, va, andiamo, andate, vanno.\n**stare**: sto, stai, sta, stiamo, state, stanno.\n**venire**: vengo, vieni, viene, veniamo, venite, vengono."
 },
 "a2_negazione": {
  "title": "Negation (non, dubbel negation)",
  "rule": "**non** står framför verbet: *Non parlo*.\nDubbel negation: **non … niente/nessuno/mai/più**: *Non ho niente, Non vado mai*.\nHålla med/säga emot: *anch'io* (jag också), **neanch'io** (inte jag heller), *io sì / io no*."
 },
 "a2_questo_quello": {
  "title": "Demonstrativa: questo / quello & quale",
  "rule": "**questo/questa/questi/queste** = denna (nära), framför vokal **quest'**.\n**quello** som den bestämda artikeln: quel, quello, quell', quella, **quei, quegli, quelle** = den där.\nFrågeord **quale/quali** = vilken."
 },
 "a2_aggettivi": {
  "title": "Adjektiv & adverb",
  "rule": "Adjektiv på **-o**: 4 former (-o/-a/-i/-e). På **-e**: 2 former (-e/-i). De anpassar sig efter substantivet och står oftast **efter det**.\nAdverb på **-mente**: från femininformen (lento → lenta → **lentamente**); på -le/-re faller e bort (gentile → **gentilmente**)."
 },
 "b1_imperfetto": {
  "title": "Imperfetto (förfluten tid: tillstånd & vanor)",
  "rule": "**Imperfetto** beskriver tillstånd, vanor och bakgrund i det förflutna ('var', 'brukade').\n-are: parl**avo**, parl**avi**, parl**ava**, parl**avamo**, parl**avate**, parl**avano**.\nViktigt: *ero, eri, era…* (essere) och *avevo…* (avere). Exempel: *Da bambina abitavo a Roma.*"
 },
 "b1_futuro": {
  "title": "Futuro semplice (framtid)",
  "rule": "**Futuro** uttrycker framtid/förmodan.\n-are/-ere: parl**erò**, parl**erai**, parl**erà**, parl**eremo**, parl**erete**, parl**eranno**.\n-ire: part**irò**… Oregelbundna: *sarò* (essere), *avrò* (avere), *andrò* (andare)."
 },
 "b1_condizionale": {
  "title": "Condizionale (artighet & önskan)",
  "rule": "**Condizionale** ('skulle') för artighet och önskningar.\nparl**erei**, parl**eresti**, parl**erebbe**, parl**eremmo**, parl**ereste**, parl**erebbero**.\nVanliga: *vorrei* (jag skulle vilja), *potrei* (jag skulle kunna), *mi piacerebbe* (jag skulle gärna)."
 },
 "b1_impf_vs_pp": {
  "title": "Imperfetto vs. Passato Prossimo",
  "rule": "**Imperfetto** = bakgrund, tillstånd, vanor, samtidiga handlingar ('var', 'alltid').\n**Passato Prossimo** = en avslutad, engångshandling.\nOfta tillsammans: *Mentre cucinavo (Imperf.), è arrivato Marco (P.P.)*."
 },
 "b1_congiuntivo": {
  "title": "Congiuntivo presente",
  "rule": "Efter *penso che, credo che, voglio che, è importante che, benché, spero che* står **Congiuntivo**.\n-are → **-i** (che io parli), -ere/-ire → **-a** (che io prenda, dorma).\nOregelbundna: **sia** (essere), **abbia** (avere), **faccia** (fare), **vada** (andare)."
 },
 "b1_ci_ne": {
  "title": "Ci & Ne",
  "rule": "**ci** ersätter en plats eller 'på det/om det': *Ci vado* (dit går jag), *Ci penso* (jag tänker på det).\n**ne** = 'av det/om det': *Ne voglio due* (jag vill ha två av dem), *Ne parliamo* (vi pratar om det)."
 },
 "b1_pronomi_combinati": {
  "title": "Pronomi combinati (glielo, me lo…)",
  "rule": "Indirekt **före** direkt, och **i → e**: mi+lo = **me lo**, ti+la = **te la**, ci+lo = **ce lo**, vi+le = **ve le**.\ngli/le + lo/la/li/le smälter samman till **glielo, gliela, glieli, gliele** (för både honom OCH henne)."
 },
 "b1_relative": {
  "title": "Relativsatser (che, cui)",
  "rule": "**che** = som (subjekt eller objekt, utan preposition): *Il libro **che** leggo*.\n**cui** = efter en **preposition**: *la città in **cui** abito, l'amica con **cui** esco, il motivo per **cui**…*"
 },
 "b1_trapassato": {
  "title": "Trapassato Prossimo (förförfluten tid)",
  "rule": "**Trapassato** beskriver något som hade hänt **före** en annan händelse i det förflutna ('hade gjort').\nBildas med **imperfetto av avere/essere + particip**: *avevo mangiato, ero andato/a*."
 },
 "b1_imperativo": {
  "title": "Imperativ (befallning/uppmaning)",
  "rule": "**Informellt (tu):** -are → **-a** (parla!), -ere/-ire → **-i** (prendi!, dormi!).\n**Nekad (tu):** non + infinitiv → *non parlare!*\n**Artigt (Lei):** parli!, prenda!, dorma!\nOregelbundna (tu): **va', fa', da', di', sta'**."
 }
};
  SV.gramEx = {
 "Städte → **a**.": "Städer → **a**.",
 "Regionen → **in** (ohne Artikel).": "Regioner → **in** (utan artikel).",
 "Länder → **in**.": "Länder → **in**.",
 "Verkehrsmittel → **in macchina**.": "Transportmedel → **in macchina**.",
 "Abitiamo ___ Roma. (in einer Stadt)": "Abitiamo ___ Roma. (i en stad)",
 "Stadt → a Roma.": "Stad → a Roma.",
 "*partire per + Ort*: **per la Sardegna** (mit Artikel).": "*partire per + plats*: **per la Sardegna** (med artikel).",
 "Vado ___ treno. (Verkehrsmittel)": "Vado ___ treno. (transportmedel)",
 "Zugehörigkeit → **di**.": "Tillhörighet → **di**.",
 "'zum Arzt' (zu einer Person) → da+il = **dal**.": "'till läkaren' (till en person) → da+il = **dal**.",
 "bei jemandem → da+i = dai nonni.": "hos någon → da+i = dai nonni.",
 "Zugehörigkeit → di+il = **del**.": "Tillhörighet → di+il = **del**.",
 "-care bekommt ein **h** vor -i: **cerchi**.": "-care får ett **h** framför -i: **cerchi**.",
 "-gare bekommt ein **h** vor -iamo: **paghiamo**.": "-gare får ett **h** framför -iamo: **paghiamo**.",
 "-care: **giochi** (h vor -i).": "-care: **giochi** (h framför -i).",
 "-iare: nur **ein i** → **mangi**.": "-iare: bara **ett i** → **mangi**.",
 "-care: **cerchi** (h vor -i).": "-care: **cerchi** (h framför -i).",
 "-care: **cerchiamo** (h vor -iamo).": "-care: **cerchiamo** (h framför -iamo).",
 "-gare: **paghi** (h vor -i).": "-gare: **paghi** (h framför -i).",
 "-care: **giochiamo** (h vor -iamo).": "-care: **giochiamo** (h framför -iamo).",
 "-gare: **spieghi** (h vor -i).": "-gare: **spieghi** (h framför -i).",
 "-iare: nur ein i → **mangi**.": "-iare: bara ett i → **mangi**.",
 "-iare: **mangiamo** (ein i).": "-iare: **mangiamo** (ett i).",
 "-ciare: ein i → **cominciamo**.": "-ciare: ett i → **cominciamo**.",
 "-iare: ein i → **studi**.": "-iare: ett i → **studi**.",
 "fare → fatto (mit avere).": "fare → fatto (med avere).",
 "dormire → dormito (mit avere).": "dormire → dormito (med avere).",
 "Wetter mit fare: ha fatto bel tempo.": "Väder med fare: ha fatto bel tempo.",
 "Familie Singular → ohne Artikel: **mio marito**.": "Familj singular → utan artikel: **mio marito**.",
 "feminin Plural: **le mie amiche**.": "femininum plural: **le mie amiche**.",
 "Plural → **mit** Artikel: i miei genitori.": "Plural → **med** artikel: i miei genitori.",
 "Familie Singular ohne Artikel: mia sorella.": "Familj singular utan artikel: mia sorella.",
 "Familie Singular → mia suocera.": "Familj singular → mia suocera.",
 "maskulin Plural: **i miei amici**.": "maskulinum plural: **i miei amici**.",
 "La crema è ___ borsa. (in + la)": "La crema è ___ borsa. (in + la)",
 "Vor unbestimmtem Artikel: **in un** (keine Verschmelzung).": "Framför obestämd artikel: **in un** (ingen sammansmältning).",
 "nach Modalverb angehängt & angepasst: **occuparmi**.": "efter modalverb tillagt & anpassat: **occuparmi**.",
 "'i miei amici' = direkt mask. Plural → **li**.": "'i miei amici' = direkt mask. plural → **li**.",
 "la + amo → **l'amo** (vor Vokal).": "la + amo → **l'amo** (framför vokal).",
 "vor Pronomen → **di me**.": "framför pronomen → **di me**.",
 "vor s+Konsonant → **uno**.": "framför s+konsonant → **uno**.",
 "feminin vor Vokal → **un'**.": "femininum framför vokal → **un'**.",
 "vor z → **lo**.": "framför z → **lo**.",
 "Person → **chi**.": "Person → **chi**.",
 "vor dem Verb → **non**.": "framför verbet → **non**.",
 "maskulin Singular → **questo**.": "maskulinum singular → **questo**.",
 "vor Vokal → **quest'**.": "framför vokal → **quest'**.",
 "Singular → **quale**.": "Singular → **quale**.",
 "Plural → **quali**.": "Plural → **quali**.",
 "feminin Singular → **bella**.": "femininum singular → **bella**.",
 "maskulin Plural → **piccoli**.": "maskulinum plural → **piccoli**.",
 "-e Adjektiv Plural → **verdi**.": "-e adjektiv plural → **verdi**.",
 "gentile → **gentilmente** (e fällt weg).": "gentile → **gentilmente** (e faller bort).",
 "feminin Singular → **simpatica**.": "femininum singular → **simpatica**.",
 "Gewohnheit in der Vergangenheit → **Imperfetto**.": "Vana i det förflutna → **Imperfetto**.",
 "Höflich → **Vorrei**.": "Artigt → **Vorrei**.",
 "'ich würde gern' → mi piacerebbe.": "'jag skulle gärna' → mi piacerebbe.",
 "Höflicher Konditional: **Potresti**.": "Artig konditionalis: **Potresti**.",
 "plötzliche Einzelhandlung → **Passato Prossimo**.": "plötslig enskild handling → **Passato Prossimo**.",
 "nach *benché* → Congiuntivo **sia**.": "efter *benché* → Congiuntivo **sia**.",
 "Subjekt, keine Präposition → **che**.": "Subjekt, ingen preposition → **che**.",
 "nach Präposition → **cui**.": "efter preposition → **cui**.",
 "höflich Lei → **entri!**": "artigt Lei → **entri!**",
 "unregelmäßig tu: **fa'** (auch 'fai').": "oregelbundet tu: **fa'** (även 'fai')."
};
  SV.topic = {
 "essere & avere": "essere & avere",
 "Substantive: Geschlecht, Plural & Artikel": "Substantiv: genus, plural & artikel",
 "Fragen & Fragewörter": "Frågor & frågeord",
 "Unregelmäßige Verben (fare/andare/stare/venire)": "Oregelbundna verb (fare/andare/stare/venire)",
 "Präsens regelmäßig (-are)": "Presens regelbundet (-are)",
 "Präsens regelmäßig (-ere/-ire, -isc-)": "Presens regelbundet (-ere/-ire, -isc-)",
 "Präsens: Sonderformen (h & -isc-)": "Presens: specialformer (h & -isc-)",
 "Präpositionen a/in (Orte, Verkehrsmittel)": "Prepositioner a/in (platser, transportmedel)",
 "Präpositionen da/di": "Prepositioner da/di",
 "Zusammengesetzte Präpositionen (nel, sul, al…)": "Sammansatta prepositioner (nel, sul, al…)",
 "Passato Prossimo (avere/essere)": "Passato Prossimo (avere/essere)",
 "Possessivpronomen & Familie": "Possessiva pronomen & familj",
 "Reflexive Verben (mi alzo, mi occupo…)": "Reflexiva verb (mi alzo, mi occupo…)",
 "Modalverben (potere, volere, dovere)": "Modala verb (potere, volere, dovere)",
 "Direkte & indirekte Objektpronomen": "Direkta & indirekta objektpronomen",
 "Komparativ (più… di / meno… di / come)": "Komparativ (più… di / meno… di / come)",
 "stare + gerundio & stare per": "stare + gerundio & stare per",
 "Verneinung (non, doppelte Verneinung)": "Negation (non, dubbel negation)",
 "Demonstrativa questo/quello & quale": "Demonstrativa questo/quello & quale",
 "Adjektive & Adverbien (-mente)": "Adjektiv & adverb (-mente)",
 "Imperfetto": "Imperfetto",
 "Imperfetto vs. Passato Prossimo": "Imperfetto vs. Passato Prossimo",
 "Trapassato Prossimo": "Trapassato Prossimo",
 "Futuro semplice": "Futuro semplice",
 "Condizionale presente": "Condizionale presente",
 "Congiuntivo presente": "Congiuntivo presente",
 "Ci & Ne": "Ci & Ne",
 "Pronomi combinati (glielo, me lo…)": "Pronomi combinati (glielo, me lo…)",
 "Relativsätze (che, cui)": "Relativsatser (che, cui)",
 "Imperativ (informell & höflich)": "Imperativ (informellt & artigt)"
};
})();
