/*
 * Olivias Italienisch-Trainer – Übersetzungssätze.
 * Neue Sätze einfach am Ende der Liste im gleichen Format anhängen.
 */
window.APP_DATA = {
  sentences: [
    { id: "s001", de: "Wir fahren mit dem Auto nach Bologna.", it: ["Andiamo in macchina a Bologna."], themes: ["travel"], cefr: "A2", grammar_focus: ["preposition_a_in"] },
    { id: "s002", de: "Am Samstag kommen wir in Italien an.", it: ["Sabato arriviamo in Italia."], themes: ["travel"], cefr: "A2", grammar_focus: ["preposition_in"] },
    { id: "s003", de: "Wir bleiben zwei Tage bei den Großeltern.", it: ["Restiamo due giorni dai nonni.", "Rimaniamo per due giorni dai nonni."], themes: ["travel", "family"], cefr: "A2", grammar_focus: ["preposition_per_dauer"] },
    { id: "s004", de: "In drei Tagen fahren wir ans Meer ab.", it: ["Fra tre giorni partiamo per il mare.", "Tra tre giorni partiamo per il mare."], themes: ["travel", "beach"], cefr: "A2", grammar_focus: ["preposition_fra_tra"] },
    { id: "s005", de: "Wir nehmen die Fähre nach Sardinien.", it: ["Prendiamo il traghetto per la Sardegna."], themes: ["travel"], cefr: "A2", grammar_focus: ["preposition_per_regione"] },
    { id: "s006", de: "Meine Schwiegermutter besucht uns heute Abend.", it: ["Mia suocera ci fa visita stasera.", "Mia suocera viene a trovarci stasera."], themes: ["family"], cefr: "A2", grammar_focus: ["family_no_article"] },
    { id: "s007", de: "Die Oma umarmt das Baby.", it: ["La nonna abbraccia il bambino."], themes: ["family", "baby"], cefr: "A1" },
    { id: "s008", de: "Wir verstehen uns gut mit meiner Schwiegermutter.", it: ["Andiamo d'accordo con mia suocera."], themes: ["family"], cefr: "A2" },
    { id: "s009", de: "Das Baby krabbelt zur Oma.", it: ["Il bambino gattona dalla nonna."], themes: ["baby", "family"], cefr: "A2", grammar_focus: ["preposition_da"] },
    { id: "s010", de: "Das Baby zieht sich am Sofa hoch.", it: ["Il bambino si mette in piedi al divano."], themes: ["baby"], cefr: "A2", grammar_focus: ["reflexive_verbs"] },
    { id: "s011", de: "Das Baby fällt hin und weint.", it: ["Il bambino cade e piange."], themes: ["baby"], cefr: "A1" },
    { id: "s012", de: "Der Hochstuhl ist im Restaurant.", it: ["Il seggiolone è al ristorante."], themes: ["baby", "restaurant"], cefr: "A2" },
    { id: "s013", de: "Wir setzen dem Baby das Lätzchen um.", it: ["Mettiamo il bavaglino al bambino."], themes: ["baby"], cefr: "A2", grammar_focus: ["preposition_a_indirect"] },
    { id: "s014", de: "Das Baby isst ein Stück Brot.", it: ["Il bambino mangia un pezzo di pane."], themes: ["baby", "food"], cefr: "A1" },
    { id: "s015", de: "Die Oma füttert das Baby.", it: ["La nonna dà da mangiare al bambino."], themes: ["baby", "family"], cefr: "A2" },
    { id: "s016", de: "Am Strand cremen wir das Baby mit Sonnencreme ein.", it: ["Sulla spiaggia mettiamo la crema solare al bambino."], themes: ["beach", "baby"], cefr: "A2", grammar_focus: ["preposition_su_a"] },
    { id: "s017", de: "Wir stellen den Sonnenschirm in den Sand.", it: ["Mettiamo l'ombrellone sulla sabbia."], themes: ["beach"], cefr: "A2", grammar_focus: ["preposition_su"] },
    { id: "s018", de: "Wir gehen im Meer schwimmen.", it: ["Facciamo il bagno nel mare."], themes: ["beach"], cefr: "A2", grammar_focus: ["preposition_in_nel"] },
    { id: "s019", de: "Am Meer bleiben wir zwei Wochen.", it: ["Al mare restiamo due settimane.", "Al mare rimaniamo per due settimane."], themes: ["beach"], cefr: "A2" },
    { id: "s020", de: "Am Sonntag schauen wir den Sonnenuntergang.", it: ["Domenica guardiamo il tramonto."], themes: ["beach"], cefr: "A2" },
    { id: "s021", de: "Im Restaurant essen wir Pasta.", it: ["Al ristorante mangiamo la pasta."], themes: ["restaurant"], cefr: "A1" },
    { id: "s022", de: "Wir hätten gern zwei Kaffee, bitte.", it: ["Vorremmo due caffè, per favore.", "Vorrei due caffè, per favore."], themes: ["restaurant"], cefr: "A2" },
    { id: "s023", de: "Wie viel kostet das Menü?", it: ["Quanto costa il menù?"], themes: ["restaurant"], cefr: "A1" },
    { id: "s024", de: "Wir zahlen an der Kasse.", it: ["Paghiamo alla cassa."], themes: ["restaurant", "shopping"], cefr: "A2", grammar_focus: ["preposition_a"] },
    { id: "s025", de: "Ich habe vor, heute Abend zu kochen.", it: ["Ho intenzione di cucinare stasera."], themes: ["food", "routine"], cefr: "A2", grammar_focus: ["avere_intenzione_di"] },
    { id: "s026", de: "Während das Baby schläft, koche ich.", it: ["Mentre il bambino dorme, cucino."], themes: ["routine", "baby"], cefr: "A2", grammar_focus: ["mentre"] },
    { id: "s027", de: "Ich habe heute Morgen gefrühstückt.", it: ["Stamattina ho fatto colazione."], themes: ["routine", "food"], cefr: "A2", grammar_focus: ["passato_prossimo"] },
    { id: "s028", de: "Wir sind gestern Abend ins Restaurant gegangen.", it: ["Ieri sera siamo andati al ristorante."], themes: ["restaurant", "routine"], cefr: "A2", grammar_focus: ["passato_prossimo_essere"] },
    { id: "s029", de: "Das Baby hat den ganzen Tag geschlafen.", it: ["Il bambino ha dormito tutto il giorno."], themes: ["baby"], cefr: "A2", grammar_focus: ["passato_prossimo"] },
    { id: "s030", de: "Ich rufe meine Mutter an.", it: ["Chiamo la mia mamma.", "Chiamo mia mamma."], themes: ["phone", "family"], cefr: "A1", grammar_focus: ["chiamare_no_con"] },
    { id: "s031", de: "Wer spricht? Hier ist Anna.", it: ["Chi parla? Sono Anna."], themes: ["phone"], cefr: "A1", grammar_focus: ["chi_vs_che"] },
    { id: "s032", de: "Ich habe einen Bruder, der in Italien lebt.", it: ["Ho un fratello che vive in Italia."], themes: ["family"], cefr: "A2", grammar_focus: ["che_relative"] },
    { id: "s033", de: "Meine Freundinnen kommen heute Abend zu mir.", it: ["Le mie amiche vengono da me stasera."], themes: ["family"], cefr: "A2", grammar_focus: ["possessive_agreement", "preposition_da"] },
    { id: "s034", de: "Kommst du mit mir in den Park?", it: ["Vieni con me al parco?"], themes: ["family"], cefr: "A2", grammar_focus: ["preposition_con_a"] },
    { id: "s035", de: "Ich gehe zum Arzt.", it: ["Vado dal medico."], themes: ["routine"], cefr: "A2", grammar_focus: ["preposition_da"] },
    { id: "s036", de: "Ich wohne in einem großen Apartment.", it: ["Abito in un appartamento grande."], themes: ["home"], cefr: "A2", grammar_focus: ["in_un"] },
    { id: "s037", de: "Der Kinderwagen ist im Auto.", it: ["Il passeggino è in macchina."], themes: ["baby", "travel"], cefr: "A2" },
    { id: "s038", de: "Wir machen einen Spaziergang mit dem Kinderwagen.", it: ["Facciamo una passeggiata con il passeggino."], themes: ["baby", "routine"], cefr: "A2" },
    { id: "s039", de: "Der Großvater spielt mit dem Baby.", it: ["Il nonno gioca con il bambino."], themes: ["family", "baby"], cefr: "A1" },
    { id: "s040", de: "Ich bin müde, aber glücklich.", it: ["Sono stanca ma felice."], themes: ["emotions"], cefr: "A1", grammar_focus: ["essere_adjective"] },
    { id: "s041", de: "Mir geht's gut, danke.", it: ["Sto bene, grazie."], themes: ["emotions", "phone"], cefr: "A1", grammar_focus: ["stare_bene"] },
    { id: "s042", de: "Ich bin schläfrig.", it: ["Ho sonno."], themes: ["emotions"], cefr: "A1", grammar_focus: ["avere_noun"] },
    { id: "s043", de: "Heute ist es warm.", it: ["Oggi fa caldo."], themes: ["weather"], cefr: "A1", grammar_focus: ["fare_weather"] },
    { id: "s044", de: "Es hat schönes Wetter gemacht.", it: ["Ha fatto bel tempo."], themes: ["weather"], cefr: "A2", grammar_focus: ["passato_prossimo_weather"] },
    { id: "s045", de: "Mitte August fahren wir nach Bologna.", it: ["A metà agosto partiamo per Bologna."], themes: ["travel", "time"], cefr: "A2" },
    { id: "s046", de: "Wir verbringen den Rest des Sommers am Meer.", it: ["Passiamo il resto dell'estate al mare."], themes: ["beach", "time"], cefr: "B1" },
    { id: "s047", de: "Das ist das Auto meiner Schwiegermutter.", it: ["Questa è la macchina di mia suocera."], themes: ["family", "travel"], cefr: "A2", grammar_focus: ["questo_agreement", "preposition_di"] },
    { id: "s048", de: "Ich bin gerade dabei, das Baby anzuziehen.", it: ["Sto per vestire il bambino."], themes: ["baby", "routine"], cefr: "B1", grammar_focus: ["stare_per"] },
    { id: "s049", de: "Die Fähre ist kurz davor abzufahren.", it: ["Il traghetto sta per partire."], themes: ["travel"], cefr: "B1", grammar_focus: ["stare_per"] },
    { id: "s050", de: "Ich sehe meinen Mann heute Abend.", it: ["Lo vedo stasera.", "Vedo mio marito stasera."], themes: ["family"], cefr: "A2", grammar_focus: ["direct_object_pronoun"] },
    { id: "s051", de: "Ich umarme sie.", it: ["L'abbraccio."], themes: ["family"], cefr: "A2", grammar_focus: ["pronoun_apostrophe"] },
    { id: "s052", de: "Ich kenne sie nicht.", it: ["Non li conosco.", "Non le conosco."], themes: ["family"], cefr: "A2", grammar_focus: ["non_pronoun_order"] },
    { id: "s053", de: "Meine Mutter und ich gehen ins Kino.", it: ["Mia mamma e io andiamo al cinema."], themes: ["family", "routine"], cefr: "A2", grammar_focus: ["io_e_persona_noi"] },
    { id: "s054", de: "Wir bringen ein Geschenk für die Großmutter mit.", it: ["Portiamo un regalo per la nonna."], themes: ["family"], cefr: "A2" },
    { id: "s055", de: "Ich habe vor, mich um die Wäsche zu kümmern.", it: ["Ho intenzione di occuparmi del bucato."], themes: ["home"], cefr: "B1", grammar_focus: ["reflexive_infinitive"] },
    { id: "s056", de: "Der Sonnenschirm ist auf dem Sand.", it: ["L'ombrellone è sulla sabbia."], themes: ["beach"], cefr: "A2" },
    { id: "s057", de: "Ich gehe an die Kasse.", it: ["Vado alla cassa."], themes: ["shopping"], cefr: "A2" },
    { id: "s058", de: "Wir verbringen zwei Wochen an der Küste bei den Großeltern.", it: ["Passiamo due settimane sulla costa dai nonni."], themes: ["beach", "family"], cefr: "B1" },
    { id: "s059", de: "Mein Mann kocht für uns.", it: ["Mio marito cucina per noi."], themes: ["family", "food"], cefr: "A2" },
    { id: "s060", de: "Ich komme aus Bologna.", it: ["Vengo da Bologna."], themes: ["family", "travel"], cefr: "A1", grammar_focus: ["preposition_da_origin"] }
  ]
};
